const fs = require('fs');
const path = require('path');
const dir = __dirname;
const root = path.resolve(dir, '../../..');
const data = p => 'data:image/'+(p.endsWith('.png')?'png':'webp')+';base64,'+fs.readFileSync(path.join(root,p)).toString('base64');
const logo=data('assets/brand/pf-inline.png');
const photos=[data('assets/home/lifestyle-aether-blue-hour.webp'),data('assets/products/embera/embera-ambient.png'),data('assets/home/lifestyle-ignite-after-dark.webp')];
const css=`@import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600&display=swap');
*{box-sizing:border-box}html,body{margin:0}body{background:#FEFFFD;color:#110F0A;font-family:'Work Sans',Arial,sans-serif}.art{position:relative;width:1080px;height:1350px;overflow:hidden;background:#FEFFFD}.logo{position:absolute;left:70px;top:60px;width:300px;height:85px;object-fit:contain;z-index:3}.kicker{font-size:18px;letter-spacing:3px;text-transform:uppercase;font-weight:500}.num{color:#D9772E;margin-right:20px}h1{font:400 92px/.99 Georgia,serif;letter-spacing:-3px;margin:0}p{font:400 27px/1.5 'Work Sans',Arial,sans-serif;margin:0}.rule{height:1px;background:currentColor;opacity:.22}.footer{position:absolute;left:70px;right:70px;bottom:62px;display:flex;justify-content:space-between;align-items:center;font-size:23px}.arrow{color:#D9772E;font-size:34px}.label{font-size:17px;letter-spacing:2px;text-transform:uppercase}.photo{position:absolute;width:100%;object-fit:cover;display:block}.story{height:1920px}.story .logo{top:180px}.story .footer{bottom:270px}.story h1{font-size:104px}.one{background:#110F0A;color:#FEFFFD}.one .photo{top:420px;height:810px;object-position:50% 50%}.one .header{position:absolute;top:193px;left:70px;right:70px}.one h1{margin-top:25px;font-size:86px}.one .footer{bottom:46px}.one .caption{position:absolute;top:1138px;left:70px;font-size:21px;text-shadow:0 1px 10px #000}.one.story .header{top:325px}.one.story h1{font-size:102px}.one.story .photo{top:640px;height:925px}.one.story .caption{top:1490px}.one.story .footer{bottom:250px}.two .header{position:absolute;left:70px;right:70px;top:205px}.two h1{margin-top:25px}.two .photo{top:480px;left:40px;width:1000px;height:585px;object-fit:cover}.two .copy{position:absolute;top:1100px;left:70px;right:70px}.two .footer{border-top:1px solid #d1d1cc;padding-top:24px;bottom:45px}.two.story .header{top:345px}.two.story .photo{top:675px;height:650px}.two.story .copy{top:1380px}.two.story .footer{bottom:255px}.three{background:#110F0A;color:#FEFFFD}.three .photo{height:100%;object-position:52% 50%}.three .shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(17,15,10,.8),rgba(17,15,10,.32) 38%,transparent 58%,rgba(17,15,10,.85))}.three .header{position:absolute;top:210px;left:70px;right:70px}.three h1{margin-top:26px;font-size:104px}.three .copy{position:absolute;left:70px;right:120px;bottom:165px;max-width:720px}.three .footer{border-top:1px solid #ffffff50;padding-top:24px;bottom:54px}.three.story .header{top:365px}.three.story h1{font-size:110px}.three.story .photo{object-position:53% 50%}.three.story .copy{bottom:395px}.three.story .footer{bottom:265px}`;
const cards=[
`<article class="art one FORMAT"><img class="photo" src="${photos[0]}"><img class="logo" src="${logo}"><div class="header"><div class="kicker"><span class="num">01</span>Ritualul serii</div><h1>Focul schimbă<br>ritmul serii.</h1></div><div class="caption">O lumină mai caldă. &nbsp; / &nbsp; Aether</div><div class="footer"><span>Vezi colecția</span><span class="arrow">↗</span></div></article>`,
`<article class="art two FORMAT"><img class="logo" src="${logo}"><div class="header"><div class="kicker"><span class="num">02</span>Colecția 2026</div><h1>Forme create<br>în jurul focului.</h1></div><img class="photo" src="${photos[1]}"><div class="copy"><p>Proporția, flacăra și funcția într-un singur obiect.<br>Cinci piese, nimic în plus.</p></div><div class="footer"><span>Explorează colecția</span><span class="arrow">↗</span></div></article>`,
`<article class="art three FORMAT"><img class="photo" src="${photos[2]}"><div class="shade"></div><img class="logo" src="${logo}"><div class="header"><div class="kicker"><span class="num">03</span>În jurul focului</div><h1>Locul unde<br>seara rămâne.</h1></div><div class="copy"><p>Locul unde conversația încetinește<br>și seara continuă.</p></div><div class="footer"><span>Descoperă colecția</span><span class="arrow">↗</span></div></article>`];
for(let i=0;i<3;i++)for(const format of ['post','story'])fs.writeFileSync(path.join(dir,`${String(i+1).padStart(2,'0')}-${format}.html`),`<!doctype html><html lang="ro"><meta charset="utf-8"><title>Pure Flame — Instagram</title><style>${css}</style>${cards[i].replace('FORMAT',format)}</html>`);
fs.writeFileSync(path.join(dir,'preview.html'),`<!doctype html><html lang="ro"><meta charset="utf-8"><title>Pure Flame — Social collection</title><style>body{margin:0;background:#e1e2db;color:#110f0a;padding:40px;font:16px Arial}h1{font:36px Georgia;margin:0 0 10px}p{margin-bottom:30px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}img{width:100%;display:block}a{color:inherit;text-decoration:none}.label{display:block;margin:12px 0 26px;font-size:13px;letter-spacing:1px}</style><h1>Pure Flame / În jurul focului</h1><p>Identitatea website-ului · 3 postări + 3 story-uri</p><div class="grid">${['post','story'].map(f=>[1,2,3].map(i=>`<a href="0${i}-${f}.png"><img src="0${i}-${f}.png"><span class="label">0${i} / ${f==='post'?'POST · 1080 × 1350':'STORY · 1080 × 1920'}</span></a>`).join('')).join('')}</div></html>`);
