const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../../..');
const img=p=>'data:image/'+(p.endsWith('.png')?'png':'webp')+';base64,'+fs.readFileSync(path.join(root,p)).toString('base64');
const logo=img('assets/brand/pf-inline.png'),aether=img('assets/products/aether/Aether_cut.png'),embera=img('assets/products/embera/Embera_cut.png'),flavo=img('assets/products/flavo/Flavo_cut.png'),detail=img('assets/products/embera/gallery/arzator.webp');
const css=`@import url('https://fonts.googleapis.com/css2?family=Italianno&family=Work+Sans:wght@400;500&display=swap');
*{box-sizing:border-box}html,body{margin:0;background:#FEFFFD;color:#110F0A}article{width:1080px;height:1350px;position:relative;overflow:hidden;background:#FEFFFD}.story{height:1920px}.logo{position:absolute;width:250px;height:71px;object-fit:contain;bottom:66px;left:415px}h1{font:400 72px/1.12 Georgia,serif;letter-spacing:-2px;margin:0}.sans{font-family:'Work Sans',Arial,sans-serif}.small{font:400 20px 'Work Sans',Arial,sans-serif;letter-spacing:3px;text-transform:uppercase}.script{font:400 62px/1.04 Italianno,cursive}.accent{color:#D9772E}img{display:block}.product{position:absolute;object-fit:contain}.one h1{position:absolute;top:150px;left:110px}.one .name{position:absolute;top:107px;left:112px}.one .product{left:100px;top:365px;width:880px;height:680px}.one .note{position:absolute;top:1055px;left:125px;transform:rotate(-5deg)}.one .material{position:absolute;top:345px;right:100px;transform:rotate(5deg);font-size:50px}.one svg{position:absolute;top:970px;left:380px;width:110px;height:100px}.story .logo{bottom:220px}.one.story .name{top:250px}.one.story h1{top:300px;font-size:86px}.one.story .product{top:650px;height:720px}.one.story .material{top:560px}.one.story .note{top:1445px;font-size:70px}.one.story svg{top:1340px}.two h1{position:absolute;left:90px;top:155px;font-size:70px;z-index:2}.two .name{position:absolute;left:94px;top:110px}.two .swatch{position:absolute;right:80px;top:360px;width:425px;height:520px;object-fit:cover;object-position:52% 60%}.two .product{width:980px;height:580px;left:20px;top:590px;z-index:2}.two .note{position:absolute;left:94px;top:410px;transform:rotate(-6deg);font-size:56px}.two .caption{position:absolute;left:94px;top:1130px;font:24px/1.4 'Work Sans',Arial,sans-serif}.two.story .name{top:260px}.two.story h1{top:310px;font-size:80px}.two.story .swatch{top:590px;height:600px}.two.story .note{top:630px}.two.story .product{top:915px;height:620px}.two.story .caption{top:1525px}.three h1{position:absolute;top:190px;left:80px;right:80px;text-align:center;font-size:68px}.three .product{top:470px;width:650px;height:590px}.three .left{left:-77px}.three .right{right:-80px}.three .line{position:absolute;top:505px;left:539px;width:1px;height:465px;background:#e1e2db}.three .names{position:absolute;top:1050px;left:0;width:100%;display:flex;justify-content:space-around;font:28px Georgia,serif}.three .note{position:absolute;top:1120px;text-align:center;width:100%;font-size:55px}.three.story h1{top:335px;font-size:77px}.three.story .product{top:750px;height:620px}.three.story .line{top:800px}.three.story .names{top:1400px}.three.story .note{top:1500px}`;
const arrow=`<svg viewBox="0 0 110 100" fill="none" stroke="#110F0A" stroke-width="1.6"><path d="M90 5 Q110 60 20 90 M20 90 L35 73 M20 90 L45 93"/></svg>`;
const cards=[`<article class="one FORMAT"><div class="name small">Aether</div><h1>În jurul focului.<br><span class="accent">Mai aproape.</span></h1><div class="material script">Beton fin texturat</div><img class="product" src="${aether}">${arrow}<div class="note script">Seri care rămân.</div><img class="logo" src="${logo}"></article>`,
`<article class="two FORMAT"><div class="name small">Embera</div><h1>O formă simplă.<br>O lumină <span class="accent">caldă.</span></h1><img class="swatch" src="${detail}"><div class="note script">Ritualul serii.</div><img class="product" src="${embera}"><div class="caption">Mese cu foc pentru exterior.</div><img class="logo" src="${logo}"></article>`,
`<article class="three FORMAT"><h1>Forme diferite.<br>Același <span class="accent">foc.</span></h1><img class="product left" src="${aether}"><img class="product right" src="${flavo}"><div class="line"></div><div class="names"><span>Aether</span><span>Flavo</span></div><div class="note script">Tu aduci oamenii.</div><img class="logo" src="${logo}"></article>`];
for(let i=0;i<3;i++)for(const f of ['post','story'])fs.writeFileSync(path.join(__dirname,`0${i+1}-${f}.html`),`<!doctype html><html lang="ro"><meta charset="utf-8"><title>Pure Flame — Minimal ${i+1}</title><style>${css}</style>${cards[i].replace('FORMAT',f)}</html>`);
